# Generated by Django 3.1.2 on 2020-12-15 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_scientifique', models.CharField(default='Pas de nom scientifique encodé', max_length=100)),
                ('azote_sol', models.IntegerField(default=0)),
                ('phosphore_sol', models.IntegerField(default=0)),
                ('potassium_sol', models.IntegerField(default=0)),
                ('date_semis_debut', models.DateField(default=django.utils.timezone.now)),
                ('date_semis_fin', models.DateField(default=django.utils.timezone.now)),
                ('densite_semi', models.IntegerField(default=0)),
                ('recolte_en_jours', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('info_insolite', models.TextField(blank=True, default='')),
                ('url_wiki', models.TextField(default='')),
                ('image', models.ImageField(blank=True, upload_to='./Img', verbose_name='plantes')),
                ('hauteur_arrosage', models.CharField(choices=[('haut', 'blue'), ('moyen', 'green'), ('bas', 'brown')], default='bas', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_parcelle', models.IntegerField(default=0)),
                ('localisation', models.CharField(default='', max_length=100)),
                ('code', models.CharField(default='code', max_length=255, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcelle', models.IntegerField()),
                ('date_plantation', models.DateField(default=django.utils.timezone.now)),
                ('taille_metre_carre', models.FloatField()),
                ('estUtilise', models.BooleanField(default=True)),
                ('planteId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to='appli.plantes')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonneesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception_donnee', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_exterieur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidite_exterieur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(default='code', max_length=500)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donneesUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonneesParcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception_donnee', models.DateTimeField(default=django.utils.timezone.now)),
                ('humidite_sol', models.IntegerField()),
                ('quantite_eau_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('code', models.CharField(default='code', max_length=500)),
                ('parcelleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnes', to='appli.parcelle')),
            ],
        ),
    ]
