# Generated by Django 3.1.2 on 2020-12-16 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantes',
            name='image2',
            field=models.ImageField(blank=True, upload_to='./Img', verbose_name='plantes'),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='image',
            field=models.TextField(default=''),
        ),
    ]
