# Generated by Django 3.0.6 on 2020-10-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantes',
            name='image',
            field=models.ImageField(blank=True, upload_to='media', verbose_name='plantes'),
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcelle', models.IntegerField()),
                ('taille', models.FloatField()),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Plantes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.Utilisateurs')),
            ],
        ),
    ]
