# Generated by Django 3.0.6 on 2020-10-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_auto_20201007_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantes',
            name='image',
            field=models.ImageField(blank=True, upload_to='../Img', verbose_name='plantes'),
        ),
    ]
