# Generated by Django 3.1.2 on 2020-10-29 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appli', '0003_auto_20201024_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Utilisateurs',
        ),
    ]
