# Generated by Django 3.1.2 on 2020-10-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0004_auto_20201029_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantes',
            name='image',
            field=models.ImageField(blank=True, upload_to='./Img', verbose_name='plantes'),
        ),
    ]
