# Generated by Django 3.1.2 on 2020-11-03 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0006_auto_20201102_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcelle',
            old_name='plante',
            new_name='planteId',
        ),
        migrations.RenameField(
            model_name='parcelle',
            old_name='taille',
            new_name='taille_metre_carre',
        ),
        migrations.RenameField(
            model_name='parcelle',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='plantes',
            old_name='taux_ideal_eau',
            new_name='besoin_hyrdrolique',
        ),
        migrations.AddField(
            model_name='plantes',
            name='date_semis_debut',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='plantes',
            name='date_semis_fin',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='plantes',
            name='nom_scientifique',
            field=models.CharField(default='Nom scientifique pas connu', max_length=100),
        ),
        migrations.AddField(
            model_name='plantes',
            name='recolte_en_jours',
            field=models.IntegerField(default=0),
        ),
    ]
