# Generated by Django 3.1.2 on 2020-11-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0007_auto_20201103_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plantes',
            old_name='besoin_hyrdrolique',
            new_name='besoin_hydrolique',
        ),
        migrations.AlterField(
            model_name='plantes',
            name='date_semis_debut',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='date_semis_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='nom_scientifique',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='recolte_en_jours',
            field=models.IntegerField(),
        ),
    ]
