# Generated by Django 3.1.2 on 2020-11-03 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appli', '0008_auto_20201103_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='date_plantation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='parcelle',
            name='estUtilise',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='date_semis_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='date_semis_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='nom_scientifique',
            field=models.CharField(default='Pas de nom scientifique encodé', max_length=100),
        ),
        migrations.AlterField(
            model_name='plantes',
            name='recolte_en_jours',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='DonneesUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception_donnee', models.DateTimeField(default=django.utils.timezone.now)),
                ('temperature_exterieur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humidite_exterieur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donneesUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DonneesParcelle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reception_donnee', models.DateTimeField(default=django.utils.timezone.now)),
                ('humidite_sol', models.IntegerField()),
                ('quantite_eau_litre', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donnes', to='appli.parcelle')),
            ],
        ),
    ]
