# Generated by Django 3.1.2 on 2020-11-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0009_auto_20201103_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantes',
            name='url_wiki',
            field=models.TextField(default=''),
        ),
    ]
