# Generated by Django 3.1.2 on 2020-11-09 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0011_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantes',
            name='densite_semi',
            field=models.IntegerField(default=0),
        ),
    ]
