# Generated by Django 3.1.2 on 2020-11-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0012_plantes_densite_semi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantes',
            name='besoin_hydrolique',
        ),
        migrations.AddField(
            model_name='plantes',
            name='azote_sol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantes',
            name='info_insolite',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='plantes',
            name='phosphore_sol',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plantes',
            name='potassium_sol',
            field=models.IntegerField(default=0),
        ),
    ]
