# Generated by Django 3.1.2 on 2020-12-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0013_auto_20201119_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='donneesparcelle',
            name='code',
            field=models.CharField(default='code', max_length=500),
        ),
        migrations.AddField(
            model_name='donneesuser',
            name='code',
            field=models.CharField(default='code', max_length=500),
        ),
    ]
