# Generated by Django 3.1.2 on 2020-12-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0014_auto_20201207_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='code',
            field=models.CharField(default='code', max_length=500),
        ),
    ]
