# Generated by Django 3.1.2 on 2020-12-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0015_profile_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='code',
            field=models.CharField(default='code', max_length=500),
        ),
    ]
