# Generated by Django 3.1.2 on 2020-12-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0016_parcelle_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcelle',
            name='code',
        ),
        migrations.AlterField(
            model_name='profile',
            name='code',
            field=models.CharField(default='code', max_length=500, unique=True),
        ),
    ]
