# Generated by Django 3.1.2 on 2020-12-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0017_auto_20201214_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantes',
            name='hauteur_arrosage',
            field=models.CharField(choices=[('haut', 'bleu'), ('moyen', 'vert'), ('bas', 'brun')], default='bas', max_length=100),
        ),
    ]
