# Generated by Django 3.1.2 on 2020-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0018_plantes_hauteur_arrosage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantes',
            name='hauteur_arrosage',
            field=models.CharField(choices=[('haut', 'blue'), ('moyen', 'green'), ('bas', 'brown')], default='bas', max_length=100),
        ),
    ]
